name: Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - uses: ./.github/actions/monorepo

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Shared CI checks
        run: pnpm run ci
