name: Core

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - uses: ./.github/actions/monorepo

      - name: Shared CI checks
        run: pnpm run ci
